name: upsert_gitcoin_rounds_to_round_logs

on:
  schedule:
    - cron:  '1 * * * *'
  workflow_dispatch:
  
jobs: 
  rounds_logs : 
    runs-on: windows-latest
    steps:
      - name: first-step
        run: echo "testing"
